# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.8.0a2
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod: null
domains_test: null
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 12
project_author: Tecnativa
project_license: BSL-1.0
project_name: myproject-odoo
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
smtp_relay_version: "9.0"
