{
    "name": "Auto Refresh Coupons with Delivery line",
    "version": "14.0.1.0.0",
    "summary": "Allows to auto-apply the coupons after adding delivery line",
    "author": "Ooops404, Cetmix, , Odoo Community Association (OCA)",
    "contributors": "Ooops404, Cetmix",
    "license": "LGPL-3",
    "category": "Sale",
    "website": "https://github.com/OCA/sale-promotion",
    "depends": ["sale_coupon_auto_refresh", "delivery_auto_refresh"],
    "external_dependencies": {},
    "demo": [],
    "qweb": [],
    "installable": True,
    "auto_install": True,
    "application": False,
}
